# The name of the deployment
name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    # Branched to look out for changes on
    branches: 
      [ main ]

  # Allow manually trigger of the jobs
  workflow_dispatch:      

jobs:
  # Job run image.
    build:
      runs-on: ubuntu-latest

   # Steps that need to happen in this job run.
      steps:
        # Check out the code
        - name: Check out code
          uses: actions/checkout@main

        # Log in to Azure CLI
        - name: Log in to Azure
          uses: azure/login@v1
          with:
      # Azure CLI credentials
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Build and deploy the container app
        #- name: Build and deploy Container App
        #  uses: azure/container-apps-deploy-action@v0
        #  with:
         #   acrName: acalevelupdemoacr
          #  acrUsername: ${{ secrets.REGISTRY_USERNAME }}
           # acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
           # containerAppName: acalevelupapp
           # containerAppEnvironment: acalevelupenv
           # resourceGroup: acalevelup
            # imageToDeploy: acalevelupdemoacr.azurecr.io/samples/blue5:latest
         
        - name: 'Deploy Container App'
          uses: Azure/cli@v1
          with:
            inlineScript: |
              echo "Installing containerapp extension"
              az extension add -n containerapp --yes
              echo "Starting Deploying"
              az containerapp revision copy -n srtesthelloapp -g ms-learnlive -i acalevelupdemoacr.azurecr.io/samples/green:latest
